### ISSUE TITLE
Valve Commands - Depends on #22

### ISSUE THREAD

**Issue by Pumuckl007** [rocketproplab/Base11-FC#10]
Create commands that toggle valves.
**Engine On**
Sets the valves to such a state the O2 and RP1 are flowing.
**Engine Off**
Sets the valves in such a state that no O2 or RP1 are flowing.
**Flush Tubes**
Sets the valves such that the tubes to the engine are flushed with Helium.
**Toggle Valve**
Toggles a single valve

**Comment by Pumuckl007** [comment]
This issue is available. Feel free to work on it. If you have any questions don't hesitate to ask.

**Comment by scifi4life** [comment]
When constructing commands for the valves, should I leave the body/arguments of the commands empty/commented, reference a to be created subsystem for valves or directly reference the solenoids for the valves (assuming you plan to use the same subsystem/solenoid setup used for the parachute subsystem)?

**Comment by Pumuckl007** [comment]
Sorry for the late reply. You can create stubs for any methods you need that are not directly related to the issue. Then you can extend the subsystem for unit testing purposes. For instance if you needed a valve subsystem you could create one with empty methods. Then you can extend it with a test version of the subsystem such as the private inner class TestSolenoid in TestParachuteSubsystem.java .
