### ISSUE TITLE
Implement Heartbeat - Depends on #22

### ISSUE THREAD

**Issue by Pumuckl007** [rocketproplab/Base11-FC#24]
The SCM protocol specifies that the rocket should send a heartbeat every second. This command should be a repetitive command that sends the heartbeat packet every second.

**Comment by scifi4life** [comment]
Hello, I a interested in claiming this issue, is it available for claim?

**Comment by scifi4life** [comment]
Thanks for the heads up! I asked to help with a different issue that also had the good first issue tag.
