### ISSUE TITLE
Include barometer in main chute deploy

### ISSUE THREAD

**Issue by Pumuckl007** [rocketproplab/Base11-FC#40]
Edit the Parachute subsystem update method to deploy the main chute only when in flight mode falling with an altitude below a given threshold and a barometric pressure above a given threshold.
Make sure to add a time for how many seconds these thresholds have to be exceeded before the cute is actually deployed. 
In addition, make sure to emit events for the ParachuteListener class.

**Comment by cschow-ucsd** [comment]
#46

**Comment by cschow-ucsd** [comment]
TODO:
set MAIN_CHUTE_PRESSURE and MAIN_CHUTE_PRESSURE_TIME_THRESHOLD in Settings.java
